import React from 'react';
import Image from "next/image";
import styles from "./layout.module.css";
import type { Metadata } from "next";

const {left, right, form, body} = styles;

export const metadata: Metadata = {
    title: "Sign In",
    description: "Generated by create next app",
    icons: ["/vercel.svg"],
};

export default function Layout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={body}>
                <div className={`className ${form}`}>
                   <div className={left}>
                        <Image
                            src="/shopping-online.jpg"
                            alt="Shopping Image"
                            width={500}
                            height={500}
                        />
                   </div>
                   <div className={right}>
                        {children}
                   </div>
                </div>
            </body>
        </html>
    );
}
